### ISSUE TITLE
Separate directory for assets maybe?

### ISSUE THREAD

**Issue by thymikee** [xfiveco/chisel-sample#20]
Having static assets directory separated into `assets/` is a widely used pattern and it seems easier to deal with for build/watch scripts.

**Comment by luboskmetko** [comment]
Sounds good, what would be the structure then?
- src/assets/images
- src/assets/fonts
- dist/assets/images
- dist/assets/fonts

etc.?

**Comment by thymikee** [comment]
Seems just about that 👍
