### ISSUE TITLE
How to include partials?

### ISSUE THREAD

**Issue by arturkot** [xfiveco/chisel-sample#24]
It' more of a question than a bug really. :)

Basically I've tried to do something like this: https://www.dropbox.com/s/fvmi8kikqbrf5yl/index.twig__ApplicationsMAMPhtdocsXHTMLizedchisel-samplesrctemplates_2016-07-18_08-11-27.png?dl=0 What did I do wrong?

**Comment by luboskmetko** [comment]
Hey Artur,

I found out that so your example works you should do it like this:

```
{% extends "base.twig" %}

{% block content %}
  <h1>Hello <span class="js-greeting"></span></h1>
  {% embed 'aside.twig' %}
    {% block content %}
      ??
    {% endblock %}  
  {% endembed %}
{% endblock %}
```

The aside embed needs the content block redefined and the whole thing needs to be inside the master content block because that's the only "dynamic" part of the extended base.twig.

**Comment by luboskmetko** [comment]
As a basic use case you could also create a new aside block in base.twig and than just use 

```
{% block aside %}
 custom sidebar
{% endblock %}
```

in templates.

**Comment by arturkot** [comment]
Thanks for the answer! :)
